### ISSUE TITLE
expiry time to 12 hour format?

### ISSUE THREAD

**Issue by l4n1skyy** [jbirnick/polybar-timer#7]
```
printExpiryTime () { dunstify -u low -r -12345 "Timer expires at $( date -d "$(secondsLeft) sec" +%h:%M %a)" ;}
```
![image](https://github.com/jbirnick/polybar-timer/assets/71810630/f375d353-59ff-4629-8e61-5c72c4732fba)

the whole time string disappears when i change the format

**Comment by jbirnick** [comment]
Hey! First, let me politely say that you should write an issue differently.

First of all, you should make sure that you use correct capitalization and punctuation marks.

Second, you should formulate a precise question, not just one sentence which states what happened.

Third, you should actually think about the problem and try to solve it for yourself. At the very least you must identify which software exactly causes the problem.

In your case, for example, it's pretty clear, either directly from the problem or from just executing
```bash
$ dunstify -u low -r -12345 "Timer expires at $( date -d "2000 sec" +%h:%M %a)"
date: extra operand ‘%a’
Try 'date --help' for more information.
```
, that this is not a problem of my script, but it's about passing wrong arguments to the command `date`.
For confirmation, you then could have executed:
```
$ date -d "2000 sec" +%h:%M %a
date: extra operand ‘%a’
Try 'date --help' for more information.
```
Now from the error message and the arguments it's already pretty clear that the problem is that `%a` is treated as another argument (and not together with `+%h:%M`). So you can just solve it by putting quotes around it:
```
$ date -d "2000 sec" "+%h:%M %a"
Aug:50 Mon
```
Going back to the command, you can hence fix it to:
```
printExpiryTime () { dunstify -u low -r -12345 "Timer expires at $( date -d "$(secondsLeft) sec" "+%h:%M %a")" ;}
```

I hope this gave you an idea on how to resolve your next issue ;)

**Comment by l4n1skyy** [comment]
My bad! I'm really sorry for not following the guidelines for writing an issue. I definitely should have tried out more things before writing the issue. Thank you for pointing out the mistake I made and writing the solution, I really appreciate it!
